title: 照片墙
subtitle: Take it easy
description: 放轻松
cover: 'https://avatars.githubusercontent.com/u/146502758?s=400&u=b8a39089c210f747787383af20846de9556386c8&v=4'
author: sparkzky

footer_logo: 
  use: self
  self:
    link: 'https://sparkzky.github.io/'
    src: 'https://avatars.githubusercontent.com/u/146502758?s=400&u=b8a39089c210f747787383af20846de9556386c8&v=4'

url: https://sparkzky.github.io/gallery
root: /gallery

photography_page:
  slogan: true
  slogan_descr: '火花'
  travel_slogan: true
  travel_slogan_descr: 'Sparkzky'

google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: 

follow_challenge:
  feedId: ""
  userId: ""

nav:
  地图:
    link: /gallery/location
    icon: local-two
  归档: 
    link: https://sparkzky.github.io
    icon: inbox
  随机:
    link: /gallery/random
    icon: pic
  # 查询:
  #   link: /gallery/query
  #   icon: history-query
  状态监控:
    link: /gallery/status
    icon: list-view
  时间线:
    link: /gallery/grid-all
    icon: grid-nine

thumbnail_url: https://cdn.jsdelivr.net/gh/sparkzky/gallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/sparkzky/gallery@master
backup_base_url: https://raw.githubusercontent.com/sparkzky/gallery/master
backup_thumbnail_url: https://raw.githubusercontent.com/sparkzky/gallery/thumbnail/